_BASE_: ../segmentation_base.yaml

OUTPUT_DIR: ./output/region

NAME: republicprint

PREPROCESS:
  REGION:
    REGIONS:
      [
        "date",
        "resolution",
        "page-number",
        "separator",
        "catch-word",
        "signature-mark",
        "index",
        "header",
      ]
    MERGE_REGIONS: []
    REGION_TYPE: []

MODEL:
  MODE: region

  SEM_SEG_HEAD:
    NUM_CLASSES: 9

  ROI_HEADS:
    NUM_CLASSES: 8

  WEIGHTS:

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS:
  EVAL_PERIOD: 5000

SOLVER:
  MAX_ITER: 50000
  CHECKPOINT_PERIOD: 10000
